### ISSUE TITLE
[➫] 0/35785732(0.0%)   Time: 0s/1211138h 44m 24s        objc[27359]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called. objc[27359]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.

### ISSUE THREAD

**Issue by sharkkkyu** [jorhelp/Ingram#97]
您好，这是什么意思，该怎么操作

**Comment by sharkkkyu** [comment]
[➫] 0/35785732(0.0%)   Time: 0s/1211138h 44m 24s        objc[27359]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called.
objc[27359]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.

**Comment by eyaeya** [comment]
在执行前，先执行export OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES   # 关闭 Apple 保护
